# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.controller.category_controller:
    class: AppBundle\Controller\CategoryController
    autowire: true

  app.controller.homepage_controller:
    class: AppBundle\Controller\HomepageController
    autowire: true

  app.controller.product_controller:
    class: AppBundle\Controller\ProductController
    autowire: true

  app.controller.user_controller:
    class: AppBundle\Controller\UserController
    autowire: true
    
  app.controller.faq_controller:
    class: AppBundle\Controller\FaqController
    autowire: true
    
  app.controller.contact_controller:
    class: AppBundle\Controller\ContactController
    autowire: true

  app.facade.category_facade:
    class: AppBundle\Facade\CategoryFacade
    autowire: true

  app.facade.product_facade:
    class: AppBundle\Facade\ProductFacade
    autowire: true

  app.facade.user_facade:
    class: AppBundle\Facade\UserFacade
    autowire: true
    
  app.facade.faq_facade:
    class: AppBundle\Facade\FaqFacade
    autowire: true

  app.facade.contact_facade:
    class: AppBundle\Facade\ContactFacade
    autowire: true
    
  app.repository.category_repository:
    class: AppBundle\Repository\CategoryRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Category']
    
  app.repository.faq_repository:
    class: AppBundle\Repository\FaqRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Faq']
    
  app.repository.contact_msg_repository:
    class: AppBundle\Repository\ContactMsgRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\ContactMsg']

  app.repository.product_repository:
    class: AppBundle\Repository\ProductRepository
    factory:   ['@doctrine.orm.default_entity_manager', getRepository]
    arguments: ['AppBundle\Entity\Product']

  encoder:
    class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
    arguments:
      - 13
